name: smusy_v2
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.22.0 <1.23.0'

dependencies:
  basics: ^0.4.0+1
  black_hole_flutter: ^0.2.15
  bloc: ^6.1.1
  camera: ^0.6.4+5
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  collection: ^1.14.11
  email_validator: ^1.0.5
  enum_to_string: ^1.0.14
  file_picker: ^2.1.5+1
  firebase_auth: ^0.20.0
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flutter:
    sdk: flutter
  flutter_deep_linking: ^0.1.2
  flutter_facebook_login: ^3.0.0
  flutter_keyboard_visibility: ^4.0.2
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^1.1.0
  flutter_svg: ^0.19.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  google_sign_in: ^4.5.5
  image: ^2.1.18
  infinite_scroll_pagination: ^2.2.4
  logger: ^0.9.4
  meta: ^1.1.8
  navigation_patterns:
    git:
      url: https://github.com/JonasWanke/navigation_patterns.git
      ref: b1841ad
  open_file: ^3.0.3
  package_info: ">=0.4.1 <2.0.0"
  path: ^1.7.0
  path_provider: ^1.6.27
  percent_indicator: '^2.1.7+2'
  permission_handler: ^5.0.1+1
  rxdart: ^0.25.0
  streaming_shared_preferences: ^1.0.1
  test: ^1.15.0
  time_machine: ^0.9.13
  todo: ^1.0.2
  url_launcher: ^5.7.2

dev_dependencies:
  build_runner: ^1.10.2
  extra_pedantic: ^1.2.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.5
  intl_utils: ^1.9.0

dependency_overrides:
  analyzer: ^0.41.0
  # https://github.com/rrousselGit/freezed/issues/326
  freezed: '0.12.5'
  # https://github.com/Dana-Ferguson/time_machine/issues/44
  time_machine:
    git:
      url: https://github.com/Dana-Ferguson/time_machine
      ref: 7753e0d

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
        - asset: assets/fonts/FiraSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
